default_platform(:ios)

platform :ios do
  lane :test do
    setup_app_feedback_sdk(
      project: './iOSTestApp/iOSTestApp.xcodeproj',
      scheme: 'iOSTestApp',
      configuration: 'Release',
      slack_api_token: 'your_slack_token'
    )
  end
end
